#include <bits/stdc++.h>
#define REP(i, n) for (int i = 0; (i) < (int)(n); ++(i))
#define REP3(i, m, n) for (int i = (m); (i) < (int)(n); ++(i))
#define REP_R(i, n) for (int i = (int)(n)-1; (i) >= 0; --(i))
#define REP3R(i, m, n) for (int i = (int)(n)-1; (i) >= (int)(m); --(i))
#define ALL(x) ::std::begin(x), ::std::end(x)
using namespace std;
vector<int64_t> solve(int64_t M, int64_t D, int64_t y, int64_t m, int64_t d) {
    // TODO: edit here
    vector<int64_t> out = {y, m, d};
    out[2] += 1;
    if (out[2] == D + 1) {
        out[1] += 1;
        out[2] = 1;
    }
    if (out[1] == M + 1) {
        out[0] += 1;
        out[1] = 1;
    }
    return out;
}
// generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
int main() {
    std::ios::sync_with_stdio(false);
    std::cin.tie(nullptr);
    int64_t M, D, y, m, d;
    std::cin >> M >> D >> y >> m >> d;
    auto ans = solve(M, D, y, m, d);
    std::cout << ans[0] << ' ' << ans[1] << ' ' << ans[2] << '\n';
    return 0;
}