#!/usr/bin/env python3
# from typing import *
YES = 'Yes'
NO = 'No'
# def solve(S: str) -> str:
def solve(S: str):
    pass  # TODO: edit here
    S = S.lstrip('A')
    S = S.lstrip('B')
    S = S.lstrip('C')
    if S == '': return 'Yes'
    else: return 'No'
# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    S = input()
    a = solve(S)
    print(a)
if __name__ == '__main__':
    main()