#include <bits/stdc++.h>
#define REP(i, n) for (int i = 0; (i) < (int)(n); ++(i))
#define REP3(i, m, n) for (int i = (m); (i) < (int)(n); ++(i))
#define REP_R(i, n) for (int i = (int)(n)-1; (i) >= 0; --(i))
#define REP3R(i, m, n) for (int i = (int)(n)-1; (i) >= (int)(m); --(i))
#define ALL(x) ::std::begin(x), ::std::end(x)
using namespace std;
const std::string YES = "Yes";
const std::string NO = "No";
const std::map<char, int> P =
    {
        {'A', 1},
        {'B', 2},
        {'C', 3},
        {'D', 4},
        {'E', 5}};
int distance(char a, char b) {
    int diff = abs(P.at(a) - P.at(b));
    int out = min(diff, 5 - diff);
    return out;
}
bool solve(string S, string T) {
    // TODO: edit here
    int s_dist, t_dist;
    s_dist = distance(S.at(0), S.at(1));
    t_dist = distance(T.at(0), T.at(1));
    bool ans;
    if (s_dist == t_dist)
        ans = true;
    else
        ans = false;
    return ans;
}
// generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
int main() {
    std::ios::sync_with_stdio(false);
    std::cin.tie(nullptr);
    string S, T;
    cin >> S;
    cin >> T;
    auto ans = solve(S, T);
    std::cout << (ans ? YES : NO) << '\n';
    return 0;
}