#include <bits/stdc++.h>
#define REP(i, n) for (int i = 0; (i) < (int)(n); ++(i))
#define REP3(i, m, n) for (int i = (m); (i) < (int)(n); ++(i))
#define REP_R(i, n) for (int i = (int)(n)-1; (i) >= 0; --(i))
#define REP3R(i, m, n) for (int i = (int)(n)-1; (i) >= (int)(m); --(i))
#define ALL(x) ::std::begin(x), ::std::end(x)
using namespace std;
string solve(int64_t N) {
    // TODO: edit here
    vector<int> ans;
    int64_t inp = N - 1;
    if (inp == 0) ans.push_back(0);
    while (inp >= 5) {
        /* code */
        ans.push_back(inp % 5);
        inp = inp / 5;
    }
    if (inp > 0) ans.push_back(inp);
    reverse(ans.begin(), ans.end());
    string out = "";
    for (auto &i : ans) {
        out.push_back(static_cast<char>(i * 2 + '0'));
    }
    return out;
}
// generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
int main() {
    std::ios::sync_with_stdio(false);
    std::cin.tie(nullptr);
    int64_t N;
    std::cin >> N;
    auto ans = solve(N);
    std::cout << ans << '\n';
    return 0;
}